services:
  graylog-sidecar:
    image: graylog-sidecar
    build:
      context: .
      dockerfile: docker/Dockerfile_graylog-sidecar
    environment:
        - GRAYLOG_TOKEN=${GRAYLOG_TOKEN}
        - GRAYLOG_SIDECAR_NAME=${GRAYLOG_SIDECAR_NAME}
        - GRAYLOG_SERVER=${GRAYLOG_SERVER}
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./configs/graylog-certs/:/certs/:ro
    restart: unless-stopped
    ports:
      - 514:514
    networks:
      example-internal-network:
        ipv4_address: ${LOGGER_IP}



networks:
  example-internal-network:
    name: example_internal_network