name: Call Webhook

on:
  push:
    branches:
      - master

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call image build Webhook
        run: |
          curl -X POST https://komodo.picidolgok.hu/listener/github/build/graylog-sidecar \
            -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"event": "push", "repository": "${{ github.repository }}"}'
